[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/supervisord.pid

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:octane]
command=php /var/www/html/artisan octane:start --server=roadrunner --host=0.0.0.0 --port=8080 --workers=%(ENV_OCTANE_WORKERS)s --max-requests=%(ENV_OCTANE_MAX_REQUESTS)s
directory=/var/www/html
user=www-data
autostart=true
autorestart=true
priority=20
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
